name: trading-platform-gpu
channels:
  - pytorch
  - nvidia
  - conda-forge
  - defaults
dependencies:
  - python=3.10
  - pip
  - numpy>=1.24.0,<2.0.0
  - pandas>=2.0.0
  - scikit-learn>=1.3.0
  - lightgbm>=4.0.0
  - xgboost>=2.0.0
  - catboost>=1.2.0
  - pytorch
  - torchvision
  - torchaudio
  - pytorch-cuda=12.1
  - pip:
      - -r base.txt
